# Generated by Django 5.1.3 on 2024-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('birthday', models.DateField()),
                ('passport', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
