# Generated by Django 4.2.16 on 2024-12-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
        ('courses', '0002_course_delete_tutor'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='tutors.tutor'),
        ),
    ]
