# Generated by Django 4.2.16 on 2024-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_course_group_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.CharField(default='3 months', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
