# Generated by Django 4.2.16 on 2024-12-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_duration_alter_group_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='group',
            name='price',
        ),
    ]
